### ISSUE TITLE
org-pomodoro-start

### ISSUE THREAD

**Issue by jaydixit** [lolownia/org-pomodoro#13]
Is there a way to play a different sound when a pomodoro starts?

**Comment by leoc** [comment]
Hi @srustamo,

I am sorry it took me so long. I just pushed  1.4.1 which should fix this issue. The problem was the `call-process` command, which &rest args did not take argument values as strings happily.

Normally I do not define custom values via the emacs customisation views. I simply use `custom-set-variables`.
