### ISSUE TITLE
Implement early-finish/continue with other pomodoro?

### ISSUE THREAD

**Issue by LeoUfimtsev** [lolownia/org-pomodoro#17]
Hello, 

Would it be possible to implement a function to finish a pomodor and add the time to the task?

It would also be nice for org-pomodoro to remember the last 'unfinished' time so that one can continue with another task on the remaining time.

**Comment by leoc** [comment]
Hi @LeoUfimtsev,

this is an interesting idea. I did decide against such feature, because I understood the pomodoro technique to be harsh about the constrains and individablity of pomodoros. If a pomodoro is not finished as a whole, it should not count as a full pomodoro.

So I do not know whether such a feature would be desirable.

**Comment by srustamo** [comment]
Let me upvote the "log the unfinished pomodoro" as an option.


On Feb 13, 2015, at 9:56 PM, Arthur Leonard Andersen <
notifications@github.com> wrote:

Hi @LeoUfimtsev <https://github.com/LeoUfimtsev>,

this is an interesting idea. I did decide against such feature, because I
understood the pomodoro technique to be harsh about the constrains and
individablity of pomodoros. If a pomodoro is not finished as a whole, it
should not count as a full pomodoro.

So I do not know whether such a feature would be desirable.

—
Reply to this email directly or view it on GitHub
<https://github.com/lolownia/org-pomodoro/issues/17#issuecomment-74286299>.

**Comment by leoc** [comment]
That, of course, sounds like a desirable functionality :)

**Comment by srustamo** [comment]
I hope we are talking about the same desirable functioninality :)

If I understand Leo, his first suggestion was to "add the time since a
pomodoro's start to the clocked task's LOGBOOK drawer when forcestopping a
pomodoro."

This is what I upvoted.

Actually many pomodoro implementations offer this option. I use Pomodoro in
os x, which has it too. It also has an option to log the number
of  unfinished pomodoros as statistics, which perhaps I sounded to
suggest.  That is nice to have but less useful, probably.



On Friday, February 13, 2015, Arthur Leonard Andersen <
notifications@github.com> wrote:

> That, of course, sounds like a desirable functionality :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lolownia/org-pomodoro/issues/17#issuecomment-74287853>
> .
>


-- 
Excuse brevity: on mobile.

**Comment by leoc** [comment]
Exactly that was my understanding.

Now the custom variable `org-pomodoro-keep-killed-pomodoro-time` determines whether to keep those times or not. The default is `nil` to keep the previous behaviour.

I would vote against continuing pomodoros, though.
